// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_D4Y-dEeeOGYh1tpA5WYXt00JoxNfuKk',
    appId: '1:554470271872:web:cff9ad65842e95d75caf65',
    messagingSenderId: '554470271872',
    projectId: 'verizon-usa',
    authDomain: 'verizon-usa.firebaseapp.com',
    storageBucket: 'verizon-usa.firebasestorage.app',
    measurementId: 'G-8QK0FMZM27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtwIJLhg5i-tu40yVCW25o38YqVBDe_ZE',
    appId: '1:554470271872:android:8b3006de444af85d5caf65',
    messagingSenderId: '554470271872',
    projectId: 'verizon-usa',
    storageBucket: 'verizon-usa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsshkD1Zw6PzOPWIw3T3D66JbKVnB9HII',
    appId: '1:554470271872:ios:843e55704bc8ffe85caf65',
    messagingSenderId: '554470271872',
    projectId: 'verizon-usa',
    storageBucket: 'verizon-usa.firebasestorage.app',
    iosBundleId: 'com.example.myVarizon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsshkD1Zw6PzOPWIw3T3D66JbKVnB9HII',
    appId: '1:554470271872:ios:843e55704bc8ffe85caf65',
    messagingSenderId: '554470271872',
    projectId: 'verizon-usa',
    storageBucket: 'verizon-usa.firebasestorage.app',
    iosBundleId: 'com.example.myVarizon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_D4Y-dEeeOGYh1tpA5WYXt00JoxNfuKk',
    appId: '1:554470271872:web:442a7e4ac0d29a115caf65',
    messagingSenderId: '554470271872',
    projectId: 'verizon-usa',
    authDomain: 'verizon-usa.firebaseapp.com',
    storageBucket: 'verizon-usa.firebasestorage.app',
    measurementId: 'G-V6X19YQ0R4',
  );

}